routes/web.php
<?php

use App\Http\Middleware\Activated;
use App\Http\Middleware\Admin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/cart', function () {
//     return view('web.cart');
// });

Auth::routes(['register' => false, 'verify' => true]);

Route::middleware(['auth', Activated::class])->group(function () {
    Route::prefix('admin')->group(function () {
        Route::namespace('Admin')->group(function () {
//             Route::middleware(Admin::class)->group(function () {
//             });
                        
            Route::get('config', 'ConfigController@index')->name('config.index');
            Route::post('config', 'ConfigController@change')->name('config.change');

            Route::get('ckeditor', 'CkeditorController@index');
            Route::post('ckeditor/upload', 'CkeditorController@upload')->name('ckeditor.upload');

            Route::get('/', 'HomeController@index')->name('admin');
            Route::get('profile', 'UserController@profile')->name('profile');

            // Route::post('bill-products', 'BillProductController@store')->name('bill-products.store');
            // Route::post('city-district', 'WardController@city_district')->name('wards.city_district');
            // Route::post('district-ward', 'WardController@district_ward')->name('wards.district_ward');
            Route::resource('products', 'ProductController')->except(['show']);
            // Route::post('products/read', 'ProductController@products')->name('products.read');

            // Route::post('bill-products', 'BillProductController@store')->name('bill-products.store');
            // Route::post('receipt-products', 'ReceiptProductController@store')->name('receipt-products.store');
            Route::post('products/read', 'ProductController@products')->name('products.read');
    
            // Route::put('bill-products', 'BillProductController@update')->name('bill-products.update');
            // Route::put('receipt-products', 'ReceiptProductController@update')->name('receipt-products.update');
    
            // Route::delete('bill-products', 'BillProductController@destroy')->name('bill-products.destroy');
            // Route::delete('receipt-products', 'ReceiptProductController@destroy')->name('receipt-products.destroy');

            Route::resource('products', 'ProductController')->except('show');
            // Route::post('products/{id}','ProductImageController@store')->name('product_images.store');
            // Route::get('products/{id}/create','ProductImageController@create')->name('product_images.create');
            // Route::get('products/{id}/{order}/edit','ProductImageController@edit')->name('product_images.edit');
            // Route::put('products/{id}/{order}','ProductImageController@update')->name('product_images.update');
            // Route::delete('products/{id}/{order}','ProductImageController@destroy')->name('product_images.destroy');
            
            // Route::post('receipt-products', 'ReceiptProductController@store')->name('receipt-products.store');
    
            // Route::put('bill-products', 'BillProductController@update')->name('bill-products.update');
            // Route::put('receipt-products', 'ReceiptProductController@update')->name('receipt-products.update');
    
            // Route::delete('bill-products', 'BillProductController@destroy')->name('bill-products.destroy');
            // Route::delete('receipt-products', 'ReceiptProductController@destroy')->name('receipt-products.destroy');
    
            // Route::resource('bills', 'BillController');
            Route::resource('categories', 'CategoryController')->except(['show']);
            // Route::resource('contacts', 'ContactController')->except(['create', 'edit', 'update']);
            Route::resource('contents', 'ContentController')->except('show');
            
            Route::resource('menus', 'MenuController')->except('show');
            Route::resource('sponsors', 'SponsorController')->except('show');
            Route::resource('carousels', 'CarouselController')->except('show');
            Route::resource('types', 'TypeController')->except(['show']);
            Route::resource('users', 'UserController')->except(['show']);
            Route::resource('contacts', 'ContactController');
            // Route::post('contacts', 'ContactController@show')->name('contacts.show');
            Route::resource('orders', 'OrderController');
        });
    });
});

Route::group(['middleware' => ['web']], function () {
    Route::post('axios-type', 'HomeController@type')->name('axios.type');
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('{menu}', 'HomeController@menu')->where('menu', '([A-Za-z0-9\-\/]+)');
    Route::post('admin', 'Admin\ContactController@store')->name('web.contacts.store');

    // Route::post('admin', 'Admin\PaymentController@store')->name('web.payments.store');
    Route::namespace('Web')->group(function () {
        Route::post('add-product', 'CartController@add_product')->name('add-product');
        Route::post('dat-hang', 'OrderController@store')->name('order');
    });
});

resources/views/home.blade.php
@extends('layouts.admin')

@section('content')
<div class="container mt-4">
    <div class="row justify-content-center">
        {{-- <div class="col-md-8 mb-5">
            <div class="card">
                <div class="card-header">Dashboard</div>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="card-body">
                            You are logged in!
                    </div>
                </div>
            </div>
        </div> --}}
        <div class="col-12 mx-auto">
            <div class="row">
                <div class="col-sm-6 col-lg-4 col-xl-3 mb-4">
                    <a href="{{ route('orders.index') }}">
                        <div class="card card-dash flex-fill bg-primary text-white h-100">
                            <div class="card-body py-3">
                                <div class="row no-gutters">
                                    <div class="col-4 align-self-center text-left">
                                        <i class="fas fa-file-invoice icon"></i>
                                    </div>
                                    <div class="col-8 align-self-center text-right">
                                        <p class="text-white mb-1">Đơn Đặt Hàng</p>
                                        <h3 class="text-white">{{ App\Order::all()->count() }}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 col-lg-4 col-xl-3 mb-4">
                    <a href="{{ route('contacts.index') }}">
                        <div class="card card-dash flex-fill bg-purple text-white h-100">
                            <div class="card-body py-3">
                                <div class="row no-gutters">
                                    <div class="col-4 align-self-center text-left">
                                        <i class="fas fa-envelope-open icon"></i>
                                    </div>
                                    <div class="col-8 align-self-center text-right">
                                        <p class="text-white mb-1">Mail Liên Hệ</p>
                                        <h3 class="text-white">{{ App\Contact::all()->count() }}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 col-lg-4 col-xl-3 mb-4">
                    <a href="{{ route('products.index') }}">
                        <div class="card card-dash flex-fill bg-success text-white h-100">
                            <div class="card-body py-3">
                                <div class="row no-gutters">
                                    <div class="col-4 align-self-center text-left">
                                        <i class="fas fa-truck-loading icon"></i>
                                    </div>
                                    <div class="col-8 align-self-center text-right">
                                        <p class="text-white mb-1">Sản Phẩm</p>
                                        <h3 class="text-white">{{ App\Product::all()->count() }}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 col-lg-4 col-xl-3 mb-4">
                    <a href="{{ route('contents.index') }}">
                        <div class="card card-dash flex-fill bg-brown text-white h-100">
                            <div class="card-body py-3">
                                <div class="row no-gutters">
                                    <div class="col-4 align-self-center text-left">
                                        <i class="fas fa-book icon"></i>
                                    </div>
                                    <div class="col-8 align-self-center text-right">
                                        <p class="text-white mb-1">Bài Viết</p>
                                        <h3 class="text-white">{{ App\Content::all()->count() }}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 col-lg-4 col-xl-3 mb-4">
                    <a href="{{ route('categories.index') }}">
                        <div class="card card-dash flex-fill bg-orange text-white h-100">
                            <div class="card-body py-3">
                                <div class="row no-gutters">
                                    <div class="col-4 align-self-center text-left">
                                        <i class="fas fa-bookmark icon"></i>
                                    </div>
                                    <div class="col-8 align-self-center text-right">
                                        <p class="text-white mb-1">Danh Mục</p>
                                        <h3 class="text-white">{{ App\Category::all()->count() }}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 col-lg-4 col-xl-3 mb-4">
                    <a href="{{ route('types.index') }}">
                        <div class="card card-dash flex-fill bg-warning text-white h-100">
                            <div class="card-body py-3">
                                <div class="row no-gutters">
                                    <div class="col-4 align-self-center text-left">
                                        <i class="fas fa-boxes icon"></i>
                                    </div>
                                    <div class="col-8 align-self-center text-right">
                                        <p class="text-white mb-1">Loại Sản Phẩm</p>
                                        <h3 class="text-white">{{ App\Type::all()->count() }}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 col-lg-4 col-xl-3 mb-4">
                    <a href="{{ route('sponsors.index') }}">
                        <div class="card card-dash flex-fill bg-cyan text-white h-100">
                            <div class="card-body py-3">
                                <div class="row no-gutters">
                                    <div class="col-4 align-self-center text-left">
                                        <i class="fas fa-briefcase icon"></i>
                                    </div>
                                    <div class="col-8 align-self-center text-right">
                                        <p class="text-white mb-1">Đối Tác</p>
                                        <h3 class="text-white">{{ App\Sponsor::all()->count() }}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 col-lg-4 col-xl-3 mb-4">
                    <a href="{{ route('menus.index') }}">
                        <div class="card card-dash flex-fill bg-dark text-white h-100">
                            <div class="card-body py-3">
                                <div class="row no-gutters">
                                    <div class="col-4 align-self-center text-left">
                                        <i class="fas fa-compass icon"></i>
                                    </div>
                                    <div class="col-8 align-self-center text-right">
                                        <p class="text-white mb-1">Điều Hướng</p>
                                        <h3 class="text-white">{{ App\Menu::all()->count() }}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection